# Generated by Django 4.0 on 2022-11-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=128)),
                ('price', models.PositiveIntegerField()),
                ('compare_price', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('ingredients', models.CharField(max_length=400)),
                ('added_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
