# Generated by Django 4.0 on 2022-11-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzastore', '0004_alter_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
