# Generated by Django 4.0 on 2022-11-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzastore', '0005_alter_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
