# Generated by Django 4.0 on 2022-11-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzastore', '0009_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
