# Generated by Django 4.0 on 2022-11-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzastore', '0012_order_order_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_item_quantity',
        ),
    ]
