# Generated by Django 4.0 on 2022-11-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pizzastore', '0013_remove_order_order_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=154)),
                ('city', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=160)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shippinguser', to='auth.user')),
            ],
        ),
    ]
