# Generated by Django 4.0 on 2022-11-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzastore', '0014_shippingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='bakng_time',
            field=models.CharField(default=1, max_length=128),
        ),
    ]
