# Generated by Django 4.0 on 2022-11-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzastore', '0015_pizza_bakng_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='bakng_time',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
