# Generated by Django 4.0 on 2022-11-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzastore', '0016_alter_pizza_bakng_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='bakng_time',
            new_name='baking_time',
        ),
    ]
