# Generated by Django 4.0 on 2022-11-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzastore', '0018_order_delieverd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delieverd',
            new_name='delivered',
        ),
    ]
