# Generated by Django 4.0 on 2022-11-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzastore', '0019_rename_delieverd_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='online_pay',
            field=models.BooleanField(default=False),
        ),
    ]
